name: braindler_assistant_aics_editor
description: Flutter AICS visual editor for Braindler Assistant.
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.2
  http: ^1.4.0
  uuid: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true